### ISSUE TITLE
Search not working when typing "script"

### ISSUE THREAD

**Issue by beta** [TimoZacherl/gitimoji#10]
After typing "script" in the search box, nothing is changed and still all emojis are listed.

Screenshot:

![image](https://user-images.githubusercontent.com/5000910/143534028-65824704-9452-440b-8a6c-3ab7abfb4264.png)

**Comment by lovetodream** [comment]
Thanks for reporting. I will look into this.

**Comment by VNDRN** [comment]
I think the `script` here is actually `description`, same result when typing that
