### ISSUE TITLE
Build for Apple Silicon

### ISSUE THREAD

**Issue by dudeofawesome** [TimoZacherl/gitimoji#11]
Hey, would it be possible to get a Universal build of this? Just upgraded my MacBook and would love to be able to run this app without Rosetta.

**Comment by lovetodream** [comment]
It should already run without Rosetta. Just to confirm I've downloaded the last version and it runs natively on my Mac with M1.

<img width="677" alt="Bildschirmfoto 2022-03-10 um 22 28 29" src="https://user-images.githubusercontent.com/38291523/157757849-feff29a1-6601-44f7-9c60-11fc7e614ba3.png">

What's shown inside system info > applications on your machine?
If it shows `Intel` and you restored from a Time Machine Backup, you could try to reinstall the app. Maybe that helps.

**Comment by dudeofawesome** [comment]
Ah! You're right, it is working fine. I had downloaded an older version using the link on [this page](https://timozacherl.com/apps/#/gitimoji). I think you could use `https://github.com/lovetodream/gitimoji/releases/latest/download/gitimoji.app.zip` instead.

**Comment by lovetodream** [comment]
Oh, thanks for the hint. I am already working on a new website and I will include that.
