### ISSUE TITLE
✨ Feature Proposal: Reverse lookup

### ISSUE THREAD

**Issue by jonathanloganmoran** [TimoZacherl/gitimoji#12]
### Description of the problem

I want to be able to do a 'reverse lookup' by searching with/for a specific emoji.

For example, if I wanted to find out what the "🚀" emoji means in Gitmoji language, I would try to do:
![Fig. 1. Searching for the corresponding Gitmoji description by emoji character or emoji description.](https://user-images.githubusercontent.com/22329957/190944544-f3aa9625-e2a2-41d8-8201-06962ee07b79.png)

which as of now returns nothing.

### Workaround

Currently, desired search functionality is already implemented on https://gitmoji.dev

Thanks!

**Comment by lovetodream** [comment]
Thanks for your feature request. The feature will be part of the next release

**Comment by jonathanloganmoran** [comment]
Thanks so much! Looking forward to the update 😃
