### ISSUE TITLE
🐛 Infinity Fetching bug

### ISSUE THREAD

**Issue by ningaro** [TimoZacherl/gitimoji#18]
**Description**
After pushing "Fetch" button in app settings I lost all emojis in list and nothing more happends 😳

**System**
_macOS Monterey v12.6.1
RAM 8 GB
CPU Apple M1_

**Screenshots**
<img width="442" alt="image" src="https://user-images.githubusercontent.com/23503775/218472828-d823d159-47f0-40ff-bb8a-c197c796b951.png">

<img width="592" alt="image" src="https://user-images.githubusercontent.com/23503775/218472630-d37d4d92-760c-44a4-99fa-9badad1b7487.png">

**Comment by VNDRN** [comment]
I have the same issue! 

macOS Ventura 13.2.1 
RAM 32 GB
CPU Apple M1

**Comment by lovetodream** [comment]
Sorry for the late response, the issue should be resolved with the latest release [v2.0.1](https://github.com/lovetodream/gitimoji/releases/tag/v2.0.1). Thanks for your patience

**Comment by VNDRN** [comment]
No problem! Love the work you put in!
