### ISSUE TITLE
Supporting Global Shortcuts

### ISSUE THREAD

**Issue by adhrinae** [TimoZacherl/gitimoji#2]
Thanks for the great application!

I wish I could set a keyboard shortcut for opening the Gitmoji app on the menu bar.
Sometimes It feels redundant to click the icon on the menu bar when I'm writing commit messages, looking at the code editor.

**Comment by lovetodream** [comment]
Thanks for your feedback.
A keyboard shortcut would be a great feature for the app. I will try to add this as soon as I have time for it.
Let me know if you have a particular shortcut in your mind.

**Comment by adhrinae** [comment]
Well, It would be perfect if I can modify the shortcut as I want.
However, `Cmd + Option + G` or `Option + Control + G` would be nice, I guess.

**Comment by lovetodream** [comment]
Good point, I'll keep that in mind.

**Comment by lovetodream** [comment]
Added the ability to add a custom shortcut with v1.1.0
