### ISSUE TITLE
"Value to copy" is not saved

### ISSUE THREAD

**Issue by warrenseine** [TimoZacherl/gitimoji#3]
I use actual Unicode characters instead of GitHub-style emoji code. The feature works well, and appears to be saved. When I quit the app and open it again, the value in the drop-down list is correctly selected. However, it will still copy the emoji code unless I select the value in the drop-down list again.

Not a big deal, but I wanted to report it anyway.

**Comment by warrenseine** [comment]
Here's a fix: https://github.com/TimoZacherl/gitimoji/pull/4

First time playing with Swift, be careful!

**Comment by lovetodream** [comment]
Thanks for reporting the bug, I will have a look at your PR later today.

**Comment by lovetodream** [comment]
Closed #4
