### ISSUE TITLE
[REQUEST] HomeBrew?

### ISSUE THREAD

**Issue by ThatXliner** [TimoZacherl/gitimoji#5]
I love this app. But I have to watch the repo for new releases in order to stay up-to-date. And then, I'll need to remove and re-install this app.

It would be nice is this was available as a formulae on [Homebrew](brew.sh)

**Comment by lovetodream** [comment]
Thank you for the positive words.

I've already thought about a way of distributing updates, but I didn't consider Homebrew. I will have a look, but I don't have any experience with that side of Homebrew, so it might take some time to work on this.

**Comment by ThatXliner** [comment]
> but I don't have any experience with that side of Homebrew, so it might take some time to work on this.

Yes, same!

Tip from personal experience: despite [what homebrew says](https://docs.brew.sh/FAQ#why-does-homebrew-prefer-i-install-to-usrlocal), don't use the default installation script for installing homebrew (which installs to `/usr/local`). Instead, use [the other way](https://docs.brew.sh/Installation#untar-anywhere)

**Comment by lovetodream** [comment]
It looks like a formulae isn't what's needed here. [Homebrew Cask](https://github.com/Homebrew/homebrew-cask) is more suitable and also recommended by Homebrew for this kind of software.

**Comment by lovetodream** [comment]
I found out that someone already tried to add a Cask for gitimoji: https://github.com/Homebrew/homebrew-cask/pull/100333
It's just a matter of time until it gets merged I guess.

**Comment by ThatXliner** [comment]
> I found out that someone already tried to add a Cask for gitimoji: [Homebrew/homebrew-cask#100333](https://github.com/Homebrew/homebrew-cask/pull/100333)
> It's just a matter of time until it gets merged I guess.

Epic: it got merged. (I never knew homebrew had a centralized repository for casks 🤔 )

**Comment by lovetodream** [comment]
It didn't get merged because we don't meet the requirements as of now...

**Comment by ThatXliner** [comment]
> It didn't get merged because we don't meet the requirements as of now...

Sad. I usually don't fork repos unless I want to contribute. (TBH, I starred this mainly because **yes more swift code to read later** 😅 )

> PS: Really cool app. I might actually fork your PR and keep it in my personal tap. Again, thanks for submitting it.
> -- https://github.com/Homebrew/homebrew-cask/pull/100333#issuecomment-788208640


Epic.

---

Well, for now, we'll just need to watch the repo, remove the old app, download, and install

**Comment by lovetodream** [comment]
Yeah, maybe tell a few more people about it 😉

**Comment by dudeofawesome** [comment]
They do have [some exceptions to the notability listed here](https://docs.brew.sh/Acceptable-Casks#exceptions-to-the-notability-threshold). Specifically, part 2:
> **Submitted by a maintainer or prolific contributor.** A big part of the reasoning for the notability rule is unpopular software garners less attention and the cask gets abandoned, outdated, and broken. Someone with a proven investment in Hombrew Cask is less likely to let that happen for software they depend on.

If you're up for it, it sounds like copying my Homebrew/homebrew-cask#100333 PR but submitted by @lovetodream _might_ get it accepted?

**Comment by dudeofawesome** [comment]
Alternatively, you could host a custom tap (aka repo)
[Homebrew/brew/docs/How-to-Create-and-Maintain-a-Tap.md](https://github.com/Homebrew/brew/blob/cb509229f941b3ffaaf42b4d9393ce3f5df0ec5e/docs/How-to-Create-and-Maintain-a-Tap.md)

**Comment by lovetodream** [comment]
> If you're up for it, it sounds like copying my [Homebrew/homebrew-cask#100333](https://github.com/Homebrew/homebrew-cask/pull/100333) PR but submitted by @lovetodream _might_ get it accepted?

I am not a contributor at homebrew-cask, so unfortunately that won't get accepted as well. But as soon as we achieve the requirements I will resubmit the PR.

> Alternatively, you could host a custom tap (aka repo)
> [Homebrew/brew/docs/How-to-Create-and-Maintain-a-Tap.md](https://github.com/Homebrew/brew/blob/cb509229f941b3ffaaf42b4d9393ce3f5df0ec5e/docs/How-to-Create-and-Maintain-a-Tap.md)

As of now, this is probably the best way if you want to have "automatic" updates for the app.

**Comment by ThatXliner** [comment]
What if you add some functionality in the app itself, periodically checking the version it currently is on compared to the one on GitHub

**Comment by lovetodream** [comment]
I could definitely do this, but currently, I have very limited time to work on this project.
And to be honest I would prefer the homebrew implementation.
But feel free to submit a PR

**Comment by dudeofawesome** [comment]
Oh, you're right, I totally misread that. I thought it was saying talking about a member of the app being submitted, not a member of homebrew.
