### ISSUE TITLE
Emojis do not load properly

### ISSUE THREAD

**Issue by ThatXliner** [TimoZacherl/gitimoji#8]
On the newest release of this, the emoji list does not render. Perhaps you forgot to load it in some `View`? (I know *a smidge* of Swift but definitely not the Xcode project structure).

I like the idea of fetching emojis from the official source. That's definitely useful for the future.

**Comment by lovetodream** [comment]
I did already notice it too. Until I've fixed it, you can use the following workaround:
Close the app and reopen it, after that the list of emojis should be rendered

**Comment by ThatXliner** [comment]
> I did already notice it too. Until I've fixed it, you can use the following workaround:
> Close the app and reopen it, after that the list of emojis should be rendered

Ok, I just did that. Now I'm noticing it loading duplicate emojis.

**Comment by lovetodream** [comment]
Both issues should be fixed with this commit. I will publish a release shortly

**Comment by ThatXliner** [comment]
Fixed the issue. Thanks!
