### ISSUE TITLE
"Login app automatically" not working

### ISSUE THREAD

**Issue by lucasbento** [TimoZacherl/gitimoji#9]
Hello 👋 

First of all, thanks for creating this app, it helps me a lot on a daily-basis.

Unfortunately, as the title says, the "Login app automatically" option is not working properly, perhaps it's something with my OS (macOS Big Sur, 11.5.1).

I have tried to fix it but I have very little experience with macOS apps. I did notice that nothing is calling `toggleAutoLaunch` in `SearchVM.swift` so I changed `autoLaunchEnabled` to:

```swift
    @Published @objc dynamic var autoLaunchEnabled = false {
        didSet {
            if autoLaunchEnabled != oldValue { toggleAutoLaunch(bool: autoLaunchEnabled) }
        }
    }
```

But then I get:

```
2021-08-28 20:18:35.538251+0200 gitimoji[7040:2448086] Could not locate login item com.timozacherl.GitmojiAutoLaunchHelper in the caller's bundle
2021-08-28 20:18:35.539132+0200 gitimoji[7040:2448086] Could not enable login item: com.timozacherl.GitmojiAutoLaunchHelper: 3: No such process
```

Even though it was started properly.

Perhaps you can give me any pointers on how to debug/fix this? Then I'll gladly open a PR.

**Comment by lovetodream** [comment]
Hi,
thank you for the nice words.

This is something I wanted to fix for some time now, but it seemed like no one noticed it 😁

I'll have a closer look at it tomorrow.

**Comment by lucasbento** [comment]
Cool, let me know if you need any help 🙂

**Comment by lovetodream** [comment]
It turned out to be a nothing else than a simple typo in the name of the helper app.
And indeed the function to toggle the launch on login did never get called, I wonder why I forgot this, but nevertheless it's fixed now.
Thanks again for reporting it and pointing me into the right direction.
